project:
  type: website
  output-dir: docs

website:
  title: "2024 CCCM Cluster Update"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "CCCM Cluster Somalia [Quarto](https://cccmcluster.org/)"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css # Link to your custom CSS file

editor: source
