---
title: "Projects"
---

## Project 1
The Monthly Narrative Reporting consolidates data and information from all existing tools, not just the monthly reporting template.
As you noted, submissions via the Kobo tool have been limited, with only PSA and IRW contributing data in recent months. This data/inputs received through the Monthly Reporting Tool (Kobo) alone is insufficient to produce the comprehensive reports currently being generated.
Oscar has been compiling and sharing all quantitative information from various sources, including the Excel 4W submissions shared by partners, with the coordinators. Moreover, I have emphasized to the cluster team that IOM has consistently submitted monthly updates for all its activities through the Excel 4W/monthly reporting format since April, a submission that Oscar is also recipient of.
 
Additionally, I have already flagged to the team that the current structure, workflow, and reporting template (Monthly Reporting Tool) are not functioning effectively and need to be revisited. I have also emphasized the need to establish a clear structure to ensure that all activities from all partners are captured and to prevent the errors and omissions we have encountered in the past. We plan to bring this to the IMWG once we gain clarity on the tool’s fit-for-purpose within the cluster team.
I hope this provides clarity on the matter. Please don’t hesitate to reach out if you have further questions.

## Project 2
The Monthly Narrative Reporting consolidates data and information from all existing tools, not just the monthly reporting template.
As you noted, submissions via the Kobo tool have been limited, with only PSA and IRW contributing data in recent months. This data/inputs received through the Monthly Reporting Tool (Kobo) alone is insufficient to produce the comprehensive reports currently being generated.
Oscar has been compiling and sharing all quantitative information from various sources, including the Excel 4W submissions shared by partners, with the coordinators. Moreover, I have emphasized to the cluster team that IOM has consistently submitted monthly updates for all its activities through the Excel 4W/monthly reporting format since April, a submission that Oscar is also recipient of.
 
Additionally, I have already flagged to the team that the current structure, workflow, and reporting template (Monthly Reporting Tool) are not functioning effectively and need to be revisited. I have also emphasized the need to establish a clear structure to ensure that all activities from all partners are captured and to prevent the errors and omissions we have encountered in the past. We plan to bring this to the IMWG once we gain clarity on the tool’s fit-for-purpose within the cluster team.
I hope this provides clarity on the matter. Please don’t hesitate to reach out if you have further questions.

## Project 3
The Monthly Narrative Reporting consolidates data and information from all existing tools, not just the monthly reporting template.
As you noted, submissions via the Kobo tool have been limited, with only PSA and IRW contributing data in recent months. This data/inputs received through the Monthly Reporting Tool (Kobo) alone is insufficient to produce the comprehensive reports currently being generated.
Oscar has been compiling and sharing all quantitative information from various sources, including the Excel 4W submissions shared by partners, with the coordinators. Moreover, I have emphasized to the cluster team that IOM has consistently submitted monthly updates for all its activities through the Excel 4W/monthly reporting format since April, a submission that Oscar is also recipient of.
 
Additionally, I have already flagged to the team that the current structure, workflow, and reporting template (Monthly Reporting Tool) are not functioning effectively and need to be revisited. I have also emphasized the need to establish a clear structure to ensure that all activities from all partners are captured and to prevent the errors and omissions we have encountered in the past. We plan to bring this to the IMWG once we gain clarity on the tool’s fit-for-purpose within the cluster team.
I hope this provides clarity on the matter. Please don’t hesitate to reach out if you have further questions.